filebeat.prospectors:
- type: log
  paths:
    - /var/log/*.log
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["192.168.1.212:9092"]

  # message topic selection + partitioning
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: true

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
